### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ofadam** [TheBirdsAreSpies/LetterboxdToPlex#1]
After setting everything up as expected, I'm getting this error when running main.py:

> Traceback (most recent call last):
  File "/LetterboxdToPlex/main.py", line 35, in <module>
    main()
  File "/LetterboxdToPlex/main.py", line 24, in main
    watchlist.watchlist(plex, movies)
  File "/LetterboxdToPlex/watchlist.py", line 115, in watchlist
    is_present = any(
                    ^
TypeError: 'NoneType' object is not iterable

**Comment by TheBirdsAreSpies** [comment]
I've made some changes. Please let me know if that fixes the problem

**Comment by ofadam** [comment]
That did the trick! Thanks much!
